language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: fUToAuFmdVgTYDvHsEUlZNRg3g8LvFG2LkJSzi5sOaHG75T9RdwobcdSmofKwupAAffs+QRQN/vKys2zSf9Bln2tHZTTtIJX1tDCZw5x/02VqypSePBlIZo5VwGv32w1zAoAGGzxg9SXsL26u48pqoCVeqHZtG1k57J3MuRp+8aOEWkR1QyOmQwhXG4fijiBCEhEmugduQ4w/DKkzaY9UrYhKph4W75lqcluL30yZ7UBGLFnpzQiiTpfYmIDOf0VdjJbn3ppSc7fAcHfrgwvup7KwUiu4+Udqj4Djt6KFMKO5Tth5O2vaS3uDEbtx3cnqPf3SaQi5h09D4vqHvt9+q28oa0sm6NgUJr7Iu5+5dSm4wK3WvY2QwJKoEKM/7XXE9e1iWe3zGj29JNnwuBV+ESSHL15PAY2pqHn8W2aEMiOcwDYfYHS892PYd9BDoaOlhmni+17AR4gkPQ8PocKdRukTMXzEW6NJXctZr4M3oBpyjX3k8LCZzjUERVbeYyKyU3nUSXD7vaXon4nXEqLJEtEAbaH/4YHK0PUCVG+s7YPeVvgAKpKi5/d39EZsOFmtdwONNmPOlQIeCYwjMFpIioJ7NgZeSgHDxm4zplfmSl9+Rf1SWu6zGfwkuJtgo4PWoN/Cxgk454E8LUpD1jkyEnNIGG7v0GZ3RoOmiLjto0=
  app: limitless-taiga-69733
  on:
    all_branches: 'true'
    repo: HustinKava/Budget-Tracker
  skip_cleanup: 'true'
script:
- echo "skipping tests"
