language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Heroku-Api-Key
  app: powerful-shelf-07897
  on:
    all_branches: 'true'
    repo: HustinKava/Budget-Tracker
  skip_cleanup: 'true'
script:
- echo "skipping tests"
